<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="R3" Version="1.3.0" />
    <PackageReference Include="VitalRouter" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\tps.contract\tps.contract.csproj" />
  </ItemGroup>

</Project>
