<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.7" />
    <PackageReference Include="VitalRouter" Version="2.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\gamekit\gamekit.csproj" />
    <ProjectReference Include="..\gamekit.contract\gamekit.contract.csproj" />
    <ProjectReference Include="..\tps.csharp\tps.csharp.csproj" />
    <ProjectReference Include="..\tps.contract\tps.contract.csproj" />
  </ItemGroup>
</Project>
